"""Adiciona unidade de medida de producao na marmita e na receita do condimento da marmita

Revision ID: 164e22e1179b
Revises: 20cb75cd50b5
Create Date: 2025-05-28 17:07:14.524037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164e22e1179b'
down_revision = '20cb75cd50b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marmita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_medida_producao', sa.String(length=50), nullable=True))

    with op.batch_alter_table('marmita_condimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_do_condimento_na_marmita', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marmita_condimento', schema=None) as batch_op:
        batch_op.drop_column('unidade_do_condimento_na_marmita')

    with op.batch_alter_table('marmita', schema=None) as batch_op:
        batch_op.drop_column('unidade_medida_producao')

    # ### end Alembic commands ###
