"""Adiciona campo de unidade na receita do ingrediente do condimento

Revision ID: 20cb75cd50b5
Revises: 975d305643ae
Create Date: 2025-05-28 15:10:37.752720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20cb75cd50b5'
down_revision = '975d305643ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condimento_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_do_ingrediente_na_receita', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condimento_item', schema=None) as batch_op:
        batch_op.drop_column('unidade_do_ingrediente_na_receita')

    # ### end Alembic commands ###
