"""Torna campos de endereco e pagamento nao anulaveis

Revision ID: 51b7c145781f
Revises: 56d8a8c9eb8c
Create Date: 2025-05-23 17:08:15.854045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b7c145781f'
down_revision = '56d8a8c9eb8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.alter_column('endereco_entrega',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('forma_pagamento',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.alter_column('forma_pagamento',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('endereco_entrega',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
