"""Adiciona campos de endereco, pagamento e troco na tabela Venda (anulaveis)

Revision ID: 56d8a8c9eb8c
Revises: c685913b0796
Create Date: 2025-05-23 17:05:46.887049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d8a8c9eb8c'
down_revision = 'c685913b0796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco_entrega', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('forma_pagamento', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('troco_para', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_column('troco_para')
        batch_op.drop_column('forma_pagamento')
        batch_op.drop_column('endereco_entrega')

    # ### end Alembic commands ###
