"""Adiciona campos de endereço ao usuário

Revision ID: 65e49b1dba20
Revises: 000554e21bca
Create Date: 2025-05-23 14:42:46.975650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e49b1dba20'
down_revision = '000554e21bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cep', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('rua', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('numero', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('complemento', sa.String(length=100), nullable=True))
        batch_op.drop_column('endereco')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('complemento')
        batch_op.drop_column('numero')
        batch_op.drop_column('rua')
        batch_op.drop_column('bairro')
        batch_op.drop_column('cidade')
        batch_op.drop_column('estado')
        batch_op.drop_column('cep')

    # ### end Alembic commands ###
