"""Adiciona campo preco_unitario na tabela VendaItem

Revision ID: 9e02b1269165
Revises: 51b7c145781f
Create Date: 2025-05-23 17:11:19.321903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e02b1269165'
down_revision = '51b7c145781f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco_unitario', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda_item', schema=None) as batch_op:
        batch_op.drop_column('preco_unitario')

    # ### end Alembic commands ###
