"""Aumenta tamanho das colunas do endereço

Revision ID: c685913b0796
Revises: 65e49b1dba20
Create Date: 2025-05-23 14:46:22.194314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c685913b0796'
down_revision = '65e49b1dba20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('cep',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('cep',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)

    # ### end Alembic commands ###
